module.exports = {
  SOCKET: {
    COMMENT: 1,
    REPLY_COMMENT: 2,
    REPORT: 3,
    NOTIFY_BLOG: 4,
    REACT: 5,
    REACT_COMMENT: 6,
    REACT_COMMENT_REPLY: 7,
    NOTIFY_COMMENT_REPORTED_FROM_ADMIN: 8,
    NOTIFY_BLOG_PENDING: 9,
    NOTIFY_COURSE_PENDING: 10,
    REJECTED_COMMENT_REPORTED_FROM_ADMIN: 11,
    REJECTED_BLOG_PENDING: 12,
    REJECTED_COURSE_PENDING: 13,
  },
};
